name: Issue
on: 
  issues:
    types: opened
jobs:
  print:
    name: Printer
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Print
        run: echo "${{ toJson(github.event) }}"
      - name: Add comment
        uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This comment is from GH Action
